runtime: python27
api_version: 1
threadsafe: yes
instance_class: F4

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /vendor
  static_dir: vendor

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /data
  static_dir: data

- url: /forms
  static_dir: forms

- url: /info
  script: main.application
  login: required

- url: .*
  script: main.application

skip_files:
- analysis/
- .idea/
- .DS_Store/

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
